on:
  pull_request:
    branches: [ master ]

jobs:
  deploy-configs:
    runs-on: ubuntu-latest
    name: Deploy Configs
    steps:
      - uses: actions/checkout@v3

      - name: get commit message
        id: commitmsg
        run: echo "commitmessage=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_OUTPUT

      - name: Deploy
        uses: ./
        with:
          base-url: ${{ secrets.BASE_URL }}
          token-url: ${{ secrets.TOKEN_URL }}
          cdf-project-name: ${{ secrets.PROJECT }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          root-folder: "test_root_dir/"
          deploy: "true"
          revision-message: "${{ steps.commitmsg.outputs.commitmessage }}"